import { User } from "../user/user";
import { Event } from "../events/interface";

export const CURRENT_USER: User = {
  id: "user-1",
  name: "Alice Tan",
  email: "alice@uni.edu",
};

export const DUMMY_USERS: User[] = [
  CURRENT_USER,
  { id: "user-2", name: "Ben Cruz", email: "ben@uni.edu" },
  { id: "user-3", name: "Cara Wong", email: "cara@uni.edu" },
  { id: "user-4", name: "David Lim", email: "david@uni.edu" },
  { id: "user-5", name: "Eva Santos", email: "eva@uni.edu" },
  { id: "user-6", name: "Felix Ng", email: "felix@uni.edu" },
  { id: "user-7", name: "Grace Park", email: "grace@uni.edu" },
  { id: "user-8", name: "Henry Zhao", email: "henry@uni.edu" },
  { id: "user-9", name: "Isla Reyes", email: "isla@uni.edu" },
  { id: "user-10", name: "Jake Kim", email: "jake@uni.edu" },
];

export const DUMMY_EVENTS: Event[] = [
  {
    id: "event-1",
    title: "Orientation Week",
    description: "Welcome to uni life! Meet your peers and explore the campus.",
    location: "Main Hall",
    startTime: "2026-07-01T09:00:00Z",
    capacity: 200,
    rsvpCount: 3,
    isRsvped: false,
    attendees: [DUMMY_USERS[0], DUMMY_USERS[1], DUMMY_USERS[2]],
  },
  {
    id: "event-2",
    title: "Study Hack Workshop",
    description: "Learn evidence-based techniques to ace your exams.",
    location: "Library Room 4",
    startTime: "2026-07-05T14:00:00Z",
    capacity: 50,
    rsvpCount: 2,
    isRsvped: false,
    attendees: [DUMMY_USERS[3], DUMMY_USERS[4]],
  },
  {
    id: "event-3",
    title: "Campus Sports Day",
    description: "Inter-college athletics competition. Cheer your team on!",
    location: "Sports Oval",
    startTime: "2026-07-10T08:00:00Z",
    capacity: 500,
    rsvpCount: 5,
    isRsvped: false,
    attendees: [
      DUMMY_USERS[0],
      DUMMY_USERS[2],
      DUMMY_USERS[5],
      DUMMY_USERS[6],
      DUMMY_USERS[7],
    ],
  },
  {
    id: "event-4",
    title: "Coding Bootcamp",
    description: "Hands-on intro to web development for beginners.",
    location: "CS Lab 2",
    startTime: "2026-07-12T10:00:00Z",
    capacity: 30,
    rsvpCount: 4,
    isRsvped: false,
    attendees: [DUMMY_USERS[1], DUMMY_USERS[3], DUMMY_USERS[8], DUMMY_USERS[9]],
  },
  {
    id: "event-5",
    title: "Club Fair",
    description: "Discover and join student clubs from all faculties.",
    location: "Student Union Courtyard",
    startTime: "2026-07-15T11:00:00Z",
    capacity: 300,
    rsvpCount: 6,
    isRsvped: false,
    attendees: [
      DUMMY_USERS[0],
      DUMMY_USERS[1],
      DUMMY_USERS[4],
      DUMMY_USERS[5],
      DUMMY_USERS[6],
      DUMMY_USERS[9],
    ],
  },
  {
    id: "event-6",
    title: "Mental Health Awareness Talk",
    description: "Open discussion on student wellbeing and support resources.",
    location: "Auditorium B",
    startTime: "2026-07-18T13:00:00Z",
    capacity: 100,
    rsvpCount: 2,
    isRsvped: false,
    attendees: [DUMMY_USERS[2], DUMMY_USERS[7]],
  },
  {
    id: "event-7",
    title: "Cultural Night",
    description: "Celebrate diversity with performances, food, and art.",
    location: "Great Hall",
    startTime: "2026-07-22T18:00:00Z",
    capacity: 400,
    rsvpCount: 7,
    isRsvped: false,
    attendees: [
      DUMMY_USERS[0],
      DUMMY_USERS[1],
      DUMMY_USERS[2],
      DUMMY_USERS[3],
      DUMMY_USERS[4],
      DUMMY_USERS[8],
      DUMMY_USERS[9],
    ],
  },
  {
    id: "event-8",
    title: "Career Expo",
    description:
      "Network with top employers and explore graduate opportunities.",
    location: "Conference Centre",
    startTime: "2026-07-25T09:00:00Z",
    capacity: 250,
    rsvpCount: 3,
    isRsvped: false,
    attendees: [DUMMY_USERS[5], DUMMY_USERS[6], DUMMY_USERS[7]],
  },
  {
    id: "event-9",
    title: "Photography Walk",
    description:
      "Explore campus with a lens — guided photo walk for all skill levels.",
    location: "North Gate",
    startTime: "2026-07-28T07:30:00Z",
    capacity: 20,
    rsvpCount: 1,
    isRsvped: false,
    attendees: [DUMMY_USERS[3]],
  },
  {
    id: "event-10",
    title: "End of Semester Bash",
    description: "Wrap up the semester with music, games, and good vibes.",
    location: "Rooftop Garden",
    startTime: "2026-08-01T17:00:00Z",
    capacity: 150,
    rsvpCount: 4,
    isRsvped: false,
    attendees: [DUMMY_USERS[0], DUMMY_USERS[4], DUMMY_USERS[6], DUMMY_USERS[9]],
  },
];
