// Mocks generated by Mockito 5.4.6 from annotations
// in uni_life_rsvp_exam/test/features/home/home_page_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:uni_life_rsvp_exam/features/events/data/event.dart' as _i2;
import 'package:uni_life_rsvp_exam/features/events/domain/repository/event_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEvent_0 extends _i1.SmartFake implements _i2.Event {
  _FakeEvent_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EventRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventRepository extends _i1.Mock implements _i3.EventRepository {
  MockEventRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.Event>> getEvents() =>
      (super.noSuchMethod(
            Invocation.method(#getEvents, []),
            returnValue: _i4.Future<List<_i2.Event>>.value(<_i2.Event>[]),
          )
          as _i4.Future<List<_i2.Event>>);

  @override
  _i4.Future<_i2.Event> getEvent(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getEvent, [id]),
            returnValue: _i4.Future<_i2.Event>.value(
              _FakeEvent_0(this, Invocation.method(#getEvent, [id])),
            ),
          )
          as _i4.Future<_i2.Event>);

  @override
  _i4.Future<void> toggleEventRsvp(String? id, bool? confirm) =>
      (super.noSuchMethod(
            Invocation.method(#toggleEventRsvp, [id, confirm]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
